### ISSUE TITLE
Modulo de recent customers en dashboard

### ISSUE THREAD

**Issue by francoaldretee** [intelicasoft/equicare#28]
hacer funcional el modulo que se muestra en el dashboard de recent customers con informacion de valor

**Comment by francoaldretee** [comment]
quedo modulo de los usuarios mas activos en los utlimos 7 dias 

![image](https://github.com/user-attachments/assets/fa19a766-f395-48c8-9c7d-f7d77bb97700)

**Comment by FelipeAvila08** [comment]
No responsive
